### ISSUE TITLE
Missing Components folder for 'Crossword'

### ISSUE THREAD

**Issue by prajeshshrestha** [SolverMax/Blog#1]
I am a student pursuing my Bachelor degree in computer engineering in Nepal. I am at my last year of engineering and I am tasked with a major project, where i have pursued in Crossword Generation, in which I have been exploring different techniques like procedural generation, Back-tracking with Arc-Consistency, and on my exploration journey, I happen to stumble upon your blog post on Crossword Compilation using MILP. I was so fascinated by this idea of using MIP, but upon further exploration, I didn't find the relevant 'Components' folder insider the Crossword section to try out the code myself and explore it further. 
So, with duly respect, It would be very helpful for me to explore this technique further if you would provide the relevant and related codes to test out 'Crossword-1.ipynb' & 'Crossword-2.ipynb'. Thank you.

**Comment by SolverMax** [comment]
Thanks for your interest in our crossword modelling. The components folder has been added.
